version: '3'
services:
  crowd:
    container_name: cyb-crowd
    build: .
    volumes:
      - ~/volumes/crowd:/var/atlassian/crowd
    ports:
      - 8095:8095
    expose:
      - 8095
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_TEST=true
    networks:
      default:
        external:
          name: cyb
# vim: ft=yaml ts=2 sw=2 et
