version: '3'
services:
  crowd:
    container_name: crowd
    image: teamatldocker/crowd
    volumes:
      - /srv/volumes/crowd:/var/atlassian/crowd
      - /dev/urandom:/dev/random
    ports:
      - 8095:8095
    restart: always
    expose:
      - 8095
    environment:
      - "CROWD_URL=http://localhost:8095"
      - CROWD_PROXY_NAME=crowd.cyb.no
      - CROWD_PROXY_PORT=443
      - CROWD_PROXY_SCHEME=https
      - CROWD_CONTEXT=ROOT
      - SPLASH_CONTEXT=
      - VIRTUAL_HOST=crowd.cyb.no
      - VIRTUAL_PORT=8095
      - LETSENCRYPT_HOST=crowd.cyb.no
      - LETSENCRYPT_EMAIL=x@cyb.no

  nginx-proxy:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - cert-volume:/etc/nginx/certs:ro
      - vhost-volume:/etc/nginx/vhost.d
      - html-volume:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'

  nginx-companion:
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - cert-volume:/etc/nginx/certs:rw
      - vhost-volume:/etc/nginx/vhost.d
      - html-volume:/usr/share/nginx/html

networks:
  default:
    external:
      name: crowd

volumes:
  cert-volume:
  vhost-volume:
  html-volume:

# vim: ft=yaml ts=2 sw=2 et
