version: '2'

services:
  z-backend:
    container_name: cyb-z-backend
    build: src
    image: cyb/z-backend
    restart: unless-stopped
    volumes:
      - ./cyb/archive:/usr/src/app/archive
      - ./cyb/reports.json:/usr/src/app/reports.json
    environment:
      ARCHIVE_URL: https://in.cyb.no/z-backend/archive/

  z-backend-uglebo:
    container_name: cyb-z-backend-uglebo
    build: src
    image: cyb/z-backend
    restart: unless-stopped
    volumes:
      - ./uglebo/archive:/usr/src/app/archive
      - ./uglebo/reports.json:/usr/src/app/reports.json
      - ./uglebo/zmal.pdf:/usr/src/app/zmal.pdf
    environment:
      ARCHIVE_URL: https://in.cyb.no/z-backend-uglebo/archive/

networks:
  default:
    external:
      name: cyb
