---
- name: shallow clone of our management repository
  git: 
    repo: "{{ mgmt_git_repo }}"
    dest: "{{ mgmt_git_dest }}"
    depth: 1

- name: disable coreos metadata service
  service:
    name: coreos-metadata
    state: stopped
    enabled: no
  when: "'coreos' in group_names"


