version: '3'
services:
  datadog:
    container_name: dd-agent
    image: datadog/agent:latest
    restart: always
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_PROCESS_AGENT_ENABLED=true
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /etc/passwd:/etc/passwd:ro