version: '3'
services:
  jira:
    container_name: cyb-jira
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ~/volumes/jira:/var/atlassian/jira
    environment:
      - VIRTUAL_HOST=jira-test01.cyb.no
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_PORT=8080
      - LETSENCRYPT_EMAIL=
      - LETSENCRYPT_TEST=true
      - X_CROWD_PASSWORD=$CROWDPASS
networks:
  default:
    external:
      name: cyb

# vim: ft=yaml ts=2 sw=2 et
