version: '2'

services:
  cyb-okoreports-backend:
    image: cybernetisk/okoreports-backend
    restart: unless-stopped
    volumes:
      - okoreports-reports-cyb:/var/okoreports/reports
    env_file: .env

  cyb-okoreports-frontend:
    image: cybernetisk/okoreports-frontend
    restart: unless-stopped

networks:
  default:
    external:
      name: cyb

volumes:
  okoreports-reports-cyb:
