[crowd]
crowd.core.cyb.no

[wiki]
confluence.core.cyb.no

[jira]
jira.core.cyb.no

[all:vars]
ansible_user=core
ansible_ssh_private_key_file=/home/adrianh/gitshit/drift-hysj/ssh/id_cyb-ecdsa
ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
