version: '3'
services:
  postgres:
    # Note that https://confluence.atlassian.com/doc/supported-platforms-207488198.html 
    # Confluence only supports versions <= 9.6 and >= 9.3
    container_name: postgres
    image: postgres:9
    ports:
      - 5432:5432
    restart: always
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    resources:
      limits:
        memory: 3500M
    volumes:
      - /srv/volumes/postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: cyb
# vim: ft=yaml ts=2 sw=2 et
