# This config is meant to be consumed by the config transpiler, which will
# generate the corresponding Ignition config. Do not pass this config directly
# to instances of Container Linux.

etcd:
  # All options get passed as command line flags to etcd.
  # Any information inside curly braces comes from the machine at boot time.

  # multi_region and multi_cloud deployments need to use {PUBLIC_IPV4}
  advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  # listen on both the official ports and the legacy ports
  # legacy ports can be omitted if your application doesn't depend on them
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{PRIVATE_IPV4}:2380"
  # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
  # specify the initial size of your cluster with ?size=X
  discovery:                   "https://discovery.etcd.io/ae683d5ea1788f1d7f64cf1bf594b805"
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEA70yNGekW2IQS2tfCvxSoVmVDfgrl9C0Y+wINdUXVMIntO50iNOAAzNKDAIdzqsb7WtM/dMaFQCA88TKCDazWWvvi/9K71NJnJAB43p5Zjnyl57Eg3wHq9QST7ODPdSIuX6yHiO7iUqpC8RavHfbdgdM0g1cOdj1ObZSrCwKs6JvKG+d4O95c89TggBkgjm6M8BDmz2gjQOJMnUesH5Z0qedxOXkGNKD0q7RFOh8fgdz2W2WUimcyB1RfsKiKUSX5Zwv64AN9OBF4z+r9s6o2frr2AmHOOVGjrsB5MNIPjNJlRgndp2hTyMDwkdXlFwZmxltRwrTuHquF3IKO00e4enKpR5spMowon9QcYGfxhow+BJCFVRb1A6+wLJBcY+OKJ1qt6TeG6/fqd8C4vAXp7OzoJI4UHX5q5yvg0b/x7IbHQOd4n7FvmkTXrkn6pPWcBwYpSS4o7DdJIuje7YtwOHF+NADK/xAXkDiaI40CiNpbdqw5pqrs7Fz5ViJ6KnzhGSi4fppiuxEzgpMKbd7cyY52MkMPA9chgret03gzqX3ORsTWiJrGfoZRIPymAR1CK/d3wD44tvLPMh+QqpCTuD6ZfctUXTo1zv3k/Py2inDMwNJGSBR2jXyZmyxb36e/gx/sVf/MEYtXqP92bTlZV1q8w8zy7X1R4z8nIpUHagM= cyb@vor.ifi.uio.no'
